const USER_REGISTER_OTP_SUBJECT =
  "ONE TIME PASSWORD FOR USER REGISTERATION  - Bigg Beat";
const SENT_OTP_CODE = "0001";
const SUCCESS_CODE = "0000";
const ERROR_CODE = "9999";

module.exports = { USER_REGISTER_OTP_SUBJECT, SENT_OTP: SENT_OTP_CODE , SUCCESS_CODE , ERROR_CODE };
