const USER_REGISTER_OTP_SUBJECT =
  "VERIFY LINK FOR USER REGISTERATION  - Bigg Beat";
const SENT_OTP_CODE = "0001";
const SUCCESS_CODE = "0000";
const ERROR_CODE = "9999";
const USER_ROLE = "user";
const ADMIN_ROLE = "admin";

module.exports = { USER_REGISTER_OTP_SUBJECT, SENT_OTP: SENT_OTP_CODE , SUCCESS_CODE , ERROR_CODE, USER_ROLE, ADMIN_ROLE };
